spring:
  datasource:
    url: 'jdbc:postgresql://localhost/sweater_db'
    username: postgres
    password: '123'
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.yandex.ru
    username: densinichenko@yandex.ru
    password: hdcqotkhpqcrhuzj
    port: '465'
    protocol: smtps
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
upload:
  path: 'D:/sweater2_0/uploads'
mail:
  debug: false
recaptcha:
  secret: 6Ldj_qwqAAAAAODlRwbjuAfUP6MHZcljSnONMtZC
